In this assignment, you will apply Linear Algebra and Probability techniques to analyze the Wine
Quality Dataset. The dataset consists of 1599 rows and 12 columns, detailing various chemical
properties of red and white wines and their quality scores. Your tasks will focus on vectors,
matrices, eigenvalues, eigenvectors, and basic probability concepts. You can download the
dataset from the link given below. The dataset contains 1599 samples of wine, with features
such as acidity, alcohol content, pH, residual sugar, and others, alongside the target variable,
wine quality.

1. Load the dataset and handle any missing data by replacing null values with the mean
value of the respective column. (Score 2)

In [28]:
import pandas as pd
import numpy as np
df = pd.read_csv("winequality-red.csv",sep=";")   

print(df.columns)
print("Missing values before handling:")
print(df.isnull().sum())

df.fillna(df.mean(numeric_only=True), inplace=True)
print("\nMissing values after handling:")
print(df.isnull().sum())
print("\nDataset Preview:")
print(df.head())

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')
Missing values before handling:
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

Missing values after handling:
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

Dataset Preview:
   fixed acidity  volatile acidity  citric

2. Extract the following columns as vectors: alcohol,citric acid. (Score 2)


In [29]:
alcohol_vector = df['alcohol'].values
citric_acid_vector = df['citric acid'].values
print("Alcohol Vector:")
print(alcohol_vector)
print("\nCitric Acid Vector:")
print(citric_acid_vector)
print("\nAlcohol Vector Shape:", alcohol_vector.shape)
print("Citric Acid Vector Shape:", citric_acid_vector.shape)

Alcohol Vector:
[ 9.4  9.8  9.8 ... 11.  10.2 11. ]

Citric Acid Vector:
[0.   0.   0.04 ... 0.13 0.12 0.47]

Alcohol Vector Shape: (1599,)
Citric Acid Vector Shape: (1599,)


3. Select two features (e.g., alcohol and density) from the dataset and calculate the
covariance matrix using np.cov(X.T), where X is the feature matrix consisting of the
selected columns.(Score 2)

In [30]:
X = df[["alcohol", "density"]].values
cov_matrix = np.cov(X.T)
print("\nCovariance Matrix:")
print(cov_matrix)


Covariance Matrix:
[[ 1.13564740e+00 -9.97951790e-04]
 [-9.97951790e-04  3.56202945e-06]]


4. Perform eigen decomposition on the covariance matrix you computed in question 3.
Identify and interpret the results:Identify the top 2 eigenvalues of the covariance
matrix,Identify the corresponding eigenvectors.(Score 2)

In [32]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)
sorted_indices = np.argsort(eigenvalues)[::-1]
top_eigenvalues = eigenvalues[sorted_indices][:2]
top_eigenvectors = eigenvectors[:, sorted_indices][:, :2]
print("\nTop 2 Eigenvalues:")
print(top_eigenvalues)
print("\nCorresponding Eigenvectors:")
print(top_eigenvectors)



Eigenvalues:
[1.13564827e+00 2.68507580e-06]

Eigenvectors:
[[ 9.99999614e-01  8.78753184e-04]
 [-8.78753184e-04  9.99999614e-01]]

Top 2 Eigenvalues:
[1.13564827e+00 2.68507580e-06]

Corresponding Eigenvectors:
[[ 9.99999614e-01  8.78753184e-04]
 [-8.78753184e-04  9.99999614e-01]]


5. Which wine quality is most common in the dataset? How can you interpret the
distribution of wine quality scores? (Score 2)

In [33]:
quality_counts = df["quality"].value_counts()
print("\nWine Quality Distribution:")
print(quality_counts)
most_common_quality = quality_counts.idxmax()
print("\nMost Common Wine Quality:", most_common_quality)


Wine Quality Distribution:
quality
5    681
6    638
7    199
4     53
8     18
3     10
Name: count, dtype: int64

Most Common Wine Quality: 5
